apiRules:
# First include what we want
- include:
    uidRegex: ^OpenForge\.Cryptography\.LibOqs
- include:
    type: Namespace
- include:
    type: Class
    modifiers: ["public"]
- include:
    type: Struct
    modifiers: ["public"]
- include:
    type: Interface
    modifiers: ["public"]
- include:
    type: Enum
    modifiers: ["public"]
- include:
    type: Delegate
    modifiers: ["public"]

# Then exclude what we don't want
- exclude:
    uidRegex: ^System
- exclude:
    uidRegex: ^Microsoft
- exclude:
    uidRegex: ^Windows
- exclude:
    hasAttribute:
      uid: System.ComponentModel.EditorBrowsableAttribute
      ctorArguments:
      - System.ComponentModel.EditorBrowsableState.Never
- exclude:
    hasAttribute:
      uid: System.Runtime.CompilerServices.CompilerGeneratedAttribute
- exclude:
    type: Class
    modifiers: ["internal"]
- exclude:
    type: Struct
    modifiers: ["internal"]
- exclude:
    type: Interface
    modifiers: ["internal"]
- exclude:
    type: Enum
    modifiers: ["internal"]